"""Undo changes in ApplicationStatus

Revision ID: 120d21520bbe
Revises: 3e2980b48b2b
Create Date: 2025-07-02 03:15:48.141952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120d21520bbe'
down_revision: Union[str, Sequence[str], None] = '3e2980b48b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
