"""Change ApplicationStatus to lowercases

Revision ID: 3e2980b48b2b
Revises: 019eca6c6728
Create Date: 2025-07-02 03:12:59.351434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2980b48b2b'
down_revision: Union[str, Sequence[str], None] = '019eca6c6728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
