import os

# Database config
POSTGRESQL_USER = os.getenv('POSTGRES_USER')
POSTGRESQL_PASSWORD = os.getenv('POSTGRES_PASSWORD')
POSTGRESQL_DB = os.getenv('POSTGRES_DB')
POSTGRESQL_HOST = os.getenv('POSTGRES_SERVER')
POSTGRESQL_PORT = os.getenv('POSTGRES_PORT')

SQLALCHEMY_DATABASE_URL = (os.getenv('DATABASE_URL'))
SYNC_SQLALCHEMY_DATABASE_URL=(os.getenv('DATABASE_URL_SYNCH'))

# Pagination
DEFAULT_PAGINATION_LIMIT: int = 10

# JWT Auth
SECRET_KEY = os.getenv('SECRET_KEY')
ALGORITHM = os.getenv('ALGORITHM')
ACCESS_TOKEN_EXPIRE = os.getenv('EXPIRATION')  # In minutes